# Generated by Django 6.0.3 on 2026-04-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_plan',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
